version: '3.8'
services:
  redis_api:
    image: redis:6.2.1
    container_name: redis_calculator

  api_calculator:
    container_name: api_calculator
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      redis_api:
        condition: service_started
